title: "Burak Kaya"
logo: "img/logo.jpeg"  # Make sure this image exists in an 'img' folder in your repo
theme: jekyll-theme-minimal
description: "Portfolio of Burak Kaya, a Mechatronics Engineering and Software Engineering student."
